import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {mkdtempSync,mkdirSync,realpathSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {SignJWT} from 'jose';
import {HostManager} from '../src/host/manager.js';
import type {HostConfig} from '../src/shared/types.js';

const dirs:string[]=[];test.after(()=>dirs.forEach(dir=>rmSync(dir,{recursive:true,force:true})));
function setup(name:string){const dir=realpathSync(mkdtempSync(join(tmpdir(),`poly-storage-${name}-`)));const root=join(dir,'root');mkdirSync(root);dirs.push(dir);const config:HostConfig={hostId:`host-${name}`,accountId:'account',hostToken:'storage-host-token-with-thirty-two-characters',masterKey:'storage-master-key-with-thirty-two-characters',ipcToken:'storage-ipc-token-with-thirty-two-characters',relayUrl:'ws://127.0.0.1/ws',name:'Storage',roots:[root],dataDir:join(dir,'data')};return {root,config}}
async function call(manager:HostManager,config:HostConfig,method:string,params:Record<string,unknown>={}){const clientId='storage-client',body={operationId:randomUUID(),...params},grant=await new SignJWT({hostId:config.hostId,clientId,scope:'host',method,sessionId:body.sessionId}).setSubject(config.accountId).setProtectedHeader({alg:'HS256'}).setExpirationTime('30s').sign(new TextEncoder().encode(config.hostToken));return manager.rpc({type:'rpc',requestId:randomUUID(),clientId,channelId:'storage-channel',grant,method,params:body})}

test('SQLite read-only mode fails closed before state mutation and survives restart',async()=>{const {root,config}=setup('readonly');let manager=new HostManager(config,{detect:async()=>[]});try{manager.store.db.exec('PRAGMA query_only=ON');await assert.rejects(call(manager,config,'addProject',{name:'blocked',path:root}),(error:any)=>error.code==='JOURNAL_UNAVAILABLE');assert.equal(manager.store.projects().length,0);assert.equal(manager.store.journalFailureLatched(),true);manager.store.db.exec('PRAGMA query_only=OFF');await manager.close();manager=new HostManager(config,{detect:async()=>[]});assert.equal((await call(manager,config,'list')).host.recoveryRequired,true);await call(manager,config,'recoverHostJournal');assert.equal((await call(manager,config,'list')).host.recoveryRequired,false)}finally{await manager.close()}});

test('SQLite busy contention fails closed without applying the requested mutation',async()=>{const {root,config}=setup('busy'),manager=new HostManager(config,{detect:async()=>[]}),lock=new DatabaseSync(join(config.dataDir!,'host.sqlite'));try{manager.store.db.exec('PRAGMA busy_timeout=1');lock.exec('PRAGMA journal_mode=WAL;BEGIN IMMEDIATE');await assert.rejects(call(manager,config,'addProject',{name:'blocked',path:root}),(error:any)=>error.code==='JOURNAL_UNAVAILABLE');assert.equal(manager.store.projects().length,0);assert.equal(manager.store.journalFailureLatched(),true);lock.exec('ROLLBACK');await call(manager,config,'recoverHostJournal');assert.equal(manager.store.journalFailureLatched(),false)}finally{try{lock.exec('ROLLBACK')}catch{}lock.close();await manager.close()}});

test('SQLite full condition prevents later operations and enters durable fail-closed state',async()=>{const {root,config}=setup('full'),manager=new HostManager(config,{detect:async()=>[]});try{const count=Number((manager.store.db.prepare('PRAGMA page_count').get() as any).page_count);manager.store.db.exec(`PRAGMA max_page_count=${count+1}`);let full=false;for(let index=0;index<20&&!full;index++)try{manager.store.journal.appendFact({streamId:`host:${config.hostId}`,kind:'capacity_probe',payload:{data:'x'.repeat(64*1024),index}})}catch(error){full=/full/i.test(`${String((error as any)?.code??'')} ${String((error as any)?.message??error)}`)}assert.equal(full,true);await assert.rejects(call(manager,config,'list',{padding:'x'.repeat(64*1024)}),(error:any)=>error.code==='JOURNAL_UNAVAILABLE');assert.equal(manager.store.journalFailureLatched(),true);await assert.rejects(call(manager,config,'addProject',{name:'blocked',path:root}),(error:any)=>error.code==='JOURNAL_UNAVAILABLE');assert.equal(manager.store.projects().length,0);manager.store.db.exec('PRAGMA max_page_count=1073741823');await call(manager,config,'recoverHostJournal');assert.equal(manager.store.journalFailureLatched(),false)}finally{await manager.close()}});
