import {DatabaseSync} from 'node:sqlite';
import {mkdirSync,chmodSync,readFileSync,existsSync,statSync,lstatSync,openSync,writeSync,fsyncSync,closeSync,unlinkSync,realpathSync,renameSync} from 'node:fs';
import {join,relative,isAbsolute,dirname} from 'node:path';
import {randomUUID} from 'node:crypto';
import {Fault,type Project,type Session,type SessionSnapshot} from '../shared/types.js';
import {LocalCipher} from './crypto.js';
import {HostJournal,checkpointWalTruncated,type JournalFaults} from './journal.js';

export type CleanupFaultPoint='delete.afterUnlink';
interface HostStoreOptions{dir:string;secret:string;legacySecret?:string;hostId:string;quota?:number;days?:number;faults?:JournalFaults;cleanupFaults?:{hit(point:CleanupFaultPoint):void};preflight?:(db:DatabaseSync)=>void}
const encrypted=(value:string)=>value.startsWith('enc:v1:');

export class HostStore{
  readonly db:DatabaseSync;readonly dir:string;readonly cipher:LocalCipher;readonly journal:HostJournal;
  private quota:number;private days:number;private readonly latchPath:string;private legacyBackupActive=false;private cleanupFaults?:{hit(point:CleanupFaultPoint):void};private faults?:JournalFaults;
  constructor(options:HostStoreOptions|string,quota=128*1024*1024,days=30){
    const resolved=typeof options==='string'?{dir:options,secret:`development-only:${options}:polyhedron`,hostId:'legacy-host',quota,days}:options;
    this.dir=resolved.dir;this.quota=resolved.quota??quota;this.days=resolved.days??days;this.cleanupFaults=resolved.cleanupFaults;this.faults=resolved.faults;
    mkdirSync(this.dir,{recursive:true,mode:0o700});chmodSync(this.dir,0o700);mkdirSync(join(this.dir,'logs'),{recursive:true,mode:0o700});
    this.latchPath=join(this.dir,'journal-health.latch');
    if(!existsSync(this.latchPath))this.writeFailureLatch(false);else chmodSync(this.latchPath,0o600);
    this.db=new DatabaseSync(join(this.dir,'host.sqlite'));
    try{
      this.db.exec('PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;');const quick=this.db.prepare('PRAGMA quick_check').all() as any[];if(quick.length!==1||Object.values(quick[0]??{})[0]!=='ok')throw new Fault('INTEGRITY_CHECK_FAILED','SQLite 完整性检查失败');resolved.preflight?.(this.db);this.db.exec('PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL;');
      this.db.exec(`CREATE TABLE IF NOT EXISTS settings(id INTEGER PRIMARY KEY,data TEXT NOT NULL);CREATE TABLE IF NOT EXISTS host_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);CREATE TABLE IF NOT EXISTS legacy_runtime_map(session_id TEXT NOT NULL,legacy_runtime TEXT NOT NULL,runtime_offset INTEGER NOT NULL,PRIMARY KEY(session_id,legacy_runtime));CREATE TABLE IF NOT EXISTS legacy_backups(source TEXT NOT NULL,row_key TEXT NOT NULL,session_id TEXT,data TEXT NOT NULL,PRIMARY KEY(source,row_key));CREATE TABLE IF NOT EXISTS pending_file_deletions(id TEXT PRIMARY KEY,data TEXT NOT NULL);CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY,data TEXT NOT NULL);CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,data TEXT NOT NULL);CREATE TABLE IF NOT EXISTS snapshots(session_id TEXT,runtime TEXT,data TEXT NOT NULL,PRIMARY KEY(session_id,runtime));CREATE TABLE IF NOT EXISTS segments(id INTEGER PRIMARY KEY AUTOINCREMENT,session_id TEXT,runtime TEXT,file TEXT,size INTEGER DEFAULT 0,first_seq INTEGER,last_seq INTEGER,at TEXT);CREATE TABLE IF NOT EXISTS retention(session_id TEXT,runtime TEXT,truncated INTEGER DEFAULT 0,PRIMARY KEY(session_id,runtime));CREATE TABLE IF NOT EXISTS hooks(id TEXT PRIMARY KEY,session_id TEXT,runtime TEXT,event TEXT,native_id TEXT,at TEXT);`);
      this.cipher=new LocalCipher(resolved.secret,resolved.hostId);this.backupLegacySources(!!resolved.legacySecret);if(resolved.legacySecret&&resolved.legacySecret!==resolved.secret)this.rekey(new LocalCipher(resolved.legacySecret,resolved.hostId));this.journal=new HostJournal(this.db,this.cipher,resolved.faults);this.migrateLegacySegments();this.encryptDomainRows();this.encryptHookRows();this.migrateSnapshotKeys();this.finishPrivacyScrub();this.rebuildUsage();this.cleanupPendingFiles();this.db.prepare("INSERT INTO host_meta(key,value) VALUES ('master_key_version','host-only-v1') ON CONFLICT(key) DO UPDATE SET value=excluded.value").run();if(this.legacyBackupActive)this.db.prepare("INSERT INTO host_meta(key,value) VALUES ('legacy_migration_complete','encrypted-v2') ON CONFLICT(key) DO UPDATE SET value=excluded.value").run();
    }catch(error){if(this.legacyBackupActive&&!this.db.prepare("SELECT 1 FROM host_meta WHERE key='legacy_migration_complete' AND value='encrypted-v2'").get())try{this.restoreLegacySources()}catch{}try{this.db.close()}catch{}throw error}
  }
  private encode(value:unknown,aad:string){return this.cipher.sealJson(value,this.cipher.domainKey,aad)}
  private decode<T>(value:string,aad:string):T{return encrypted(value)?this.cipher.openJson<T>(value,this.cipher.domainKey,aad):JSON.parse(value) as T}
  private privacyScrubPending(){return !!this.db.prepare("SELECT 1 FROM host_meta WHERE key='privacy_scrub_pending' AND value='1'").get()}
  private markPrivacyScrubPending(){if(!this.privacyScrubPending()){this.db.exec('BEGIN IMMEDIATE');try{this.db.prepare("INSERT INTO host_meta(key,value) VALUES ('privacy_scrub_pending','1') ON CONFLICT(key) DO UPDATE SET value=excluded.value").run();this.db.exec('COMMIT')}catch(error){this.db.exec('ROLLBACK');throw error}}}
  private finishPrivacyScrub(){if(!this.privacyScrubPending())return;this.faults?.hit('privacy.hostBeforeScrub');checkpointWalTruncated(this.db);this.db.exec('VACUUM');checkpointWalTruncated(this.db);this.db.exec('BEGIN IMMEDIATE');try{this.db.prepare("DELETE FROM host_meta WHERE key='privacy_scrub_pending'").run();this.db.exec('COMMIT')}catch(error){this.db.exec('ROLLBACK');throw error}checkpointWalTruncated(this.db)}
  private legacyTables(){return ['host_meta','projects','sessions','snapshots','segments','retention','hooks','legacy_runtime_map','journal_streams','session_keys','journal_events','journal_operations','legacy_imports','journal_usage','journal_runtime_runs','journal_meta']}
  private backupLegacySources(force:boolean){
    if(this.db.prepare("SELECT 1 FROM host_meta WHERE key='legacy_migration_complete' AND value='encrypted-v2'").get())return;let legacy=force||Number((this.db.prepare('SELECT COUNT(*) count FROM segments').get() as any).count)>0||Number((this.db.prepare("SELECT COUNT(*) count FROM snapshots WHERE runtime GLOB '*[!0-9]*'").get() as any).count)>0||Number((this.db.prepare("SELECT COUNT(*) count FROM hooks WHERE runtime GLOB '*[!0-9]*'").get() as any).count)>0;
    if(!legacy)for(const row of this.db.prepare('SELECT data FROM sessions').all() as any[])if(!encrypted(row.data)&&JSON.parse(row.data)?.runtimeEpoch){legacy=true;break}if(!legacy)return;this.legacyBackupActive=true;if(this.db.prepare("SELECT 1 FROM host_meta WHERE key='legacy_backup_version' AND value='encrypted-v1'").get())return;
    this.db.exec('BEGIN IMMEDIATE');try{for(const source of this.legacyTables()){if(!this.db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(source))continue;let index=0;for(const row of this.db.prepare(`SELECT * FROM ${source}`).all() as any[]){if(source==='host_meta'&&String(row.key).startsWith('legacy_backup_'))continue;const rowKey=String(index++).padStart(12,'0'),sessionId=source==='sessions'?String(row.id):row.session_id?String(row.session_id):typeof row.stream_id==='string'&&row.stream_id.startsWith('session:')?row.stream_id.slice(8):null,data=this.cipher.sealJson(row,this.cipher.domainKey,`legacy-backup:${source}:${rowKey}`);this.db.prepare('INSERT INTO legacy_backups VALUES (?,?,?,?)').run(source,rowKey,sessionId,data)}}this.db.prepare("INSERT INTO host_meta(key,value) VALUES ('legacy_backup_version','encrypted-v1') ON CONFLICT(key) DO UPDATE SET value=excluded.value").run();this.db.exec('COMMIT')}catch(error){this.db.exec('ROLLBACK');throw error}
  }
  private restoreLegacySources(){
    this.db.exec('PRAGMA foreign_keys=OFF;BEGIN IMMEDIATE');try{for(const source of [...this.legacyTables()].reverse())if(this.db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(source)){if(source==='host_meta')this.db.exec("DELETE FROM host_meta WHERE key NOT LIKE 'legacy_backup_%'");else this.db.exec(`DELETE FROM ${source}`)}for(const source of this.legacyTables())for(const row of this.db.prepare('SELECT row_key,data FROM legacy_backups WHERE source=? ORDER BY row_key').all(source) as any[]){const value=this.cipher.openJson<Record<string,unknown>>(row.data,this.cipher.domainKey,`legacy-backup:${source}:${row.row_key}`),columns=Object.keys(value);this.db.prepare(`INSERT INTO ${source}(${columns.join(',')}) VALUES (${columns.map(()=>'?').join(',')})`).run(...columns.map(column=>value[column] as any))}this.db.exec('COMMIT;PRAGMA foreign_keys=ON')}catch(error){try{this.db.exec('ROLLBACK')}catch{}this.db.exec('PRAGMA foreign_keys=ON');throw error}
  }
  private encryptDomainRows(){const rows=['projects','sessions'].flatMap(table=>(this.db.prepare(`SELECT id,data FROM ${table}`).all() as any[]).filter(row=>!encrypted(row.data)).map(row=>({table,...row})));if(!rows.length)return;this.markPrivacyScrubPending();this.db.exec('BEGIN IMMEDIATE');try{for(const row of rows)this.db.prepare(`UPDATE ${row.table} SET data=? WHERE id=?`).run(this.encode(JSON.parse(row.data),`${row.table}:${row.id}`),row.id);this.db.exec('COMMIT')}catch(error){this.db.exec('ROLLBACK');throw error}}
  private encryptHookRows(){const rows=(this.db.prepare('SELECT id,native_id FROM hooks WHERE native_id IS NOT NULL').all() as any[]).filter(row=>!encrypted(row.native_id));if(!rows.length)return;this.markPrivacyScrubPending();this.db.exec('BEGIN IMMEDIATE');try{for(const row of rows)this.db.prepare('UPDATE hooks SET native_id=? WHERE id=?').run(this.encode(String(row.native_id),`hook:${row.id}`),row.id);this.db.exec('COMMIT')}catch(error){this.db.exec('ROLLBACK');throw error}}
  private rekey(previous:LocalCipher){if(this.db.prepare("SELECT 1 FROM host_meta WHERE key='master_key_version' AND value='host-only-v1'").get())return;this.markPrivacyScrubPending();this.db.exec('BEGIN IMMEDIATE');try{for(const table of ['projects','sessions'] as const)for(const row of this.db.prepare(`SELECT id,data FROM ${table}`).all() as any[])if(encrypted(row.data)){const value=previous.openJson(row.data,previous.domainKey,`${table}:${row.id}`);this.db.prepare(`UPDATE ${table} SET data=? WHERE id=?`).run(this.encode(value,`${table}:${row.id}`),row.id)}const snapshotKeyed=!!this.db.prepare("SELECT 1 FROM host_meta WHERE key='snapshot_key_version' AND value='session-v1'").get();if(!snapshotKeyed)for(const row of this.db.prepare('SELECT session_id,runtime,data FROM snapshots').all() as any[])if(encrypted(row.data)){const aad=`snapshot:${row.session_id}:${row.runtime}`,value=previous.openJson(row.data,previous.domainKey,aad);this.db.prepare('UPDATE snapshots SET data=? WHERE session_id=? AND runtime=?').run(this.encode(value,aad),row.session_id,row.runtime)}if(this.db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='session_keys'").get())for(const row of this.db.prepare('SELECT stream_id,key_cipher FROM session_keys').all() as any[]){const key=previous.unwrapKey(row.key_cipher,row.stream_id);this.db.prepare('UPDATE session_keys SET key_cipher=? WHERE stream_id=?').run(this.cipher.wrapKey(key,row.stream_id),row.stream_id)}for(const row of this.db.prepare('SELECT id,native_id FROM hooks WHERE native_id IS NOT NULL').all() as any[])if(encrypted(row.native_id)){const value=previous.openJson(row.native_id,previous.domainKey,`hook:${row.id}`);this.db.prepare('UPDATE hooks SET native_id=? WHERE id=?').run(this.cipher.sealJson(value,this.cipher.domainKey,`hook:${row.id}`),row.id)}this.db.prepare("INSERT INTO host_meta(key,value) VALUES ('master_key_version','host-only-v1') ON CONFLICT(key) DO UPDATE SET value=excluded.value").run();this.db.exec('COMMIT')}catch(error){this.db.exec('ROLLBACK');throw error}}
  private migrateSnapshotKeys(){if(this.db.prepare("SELECT 1 FROM host_meta WHERE key='snapshot_key_version' AND value='session-v1'").get())return;if(Number((this.db.prepare('SELECT COUNT(*) count FROM snapshots').get() as any).count)>0)this.markPrivacyScrubPending();this.db.exec('BEGIN IMMEDIATE');try{for(const row of this.db.prepare('SELECT session_id,runtime,data FROM snapshots').all() as any[]){const value=encrypted(row.data)?this.decode<any>(row.data,`snapshot:${row.session_id}:${row.runtime}`):JSON.parse(row.data),runtimeOffset=Number(row.runtime),streamId=`session:${row.session_id}`;if(!Number.isSafeInteger(runtimeOffset)||runtimeOffset<1)throw new Fault('LEGACY_MIGRATION_FAILED','旧版终端快照缺少可映射的运行边界');if(Number.isSafeInteger(value?.seq)){const output=this.journal.eventsAfter(streamId,runtimeOffset).find(event=>event.runtimeOffset===runtimeOffset&&event.kind==='pty_output'&&Number((event.payload as any)?.legacySequence)===Number(value.seq));value.baseOffset=output?.offset??runtimeOffset;value.headOffset=this.journal.head(streamId);delete value.seq}else{value.baseOffset=value.baseOffset??runtimeOffset;value.headOffset=value.headOffset??this.journal.head(streamId)}if(value?.session){value.session.runtimeOffset=runtimeOffset;value.session.controlOffset=null;value.session.headOffset=value.headOffset;value.session.journalState=value.session.journalState??'ready';delete value.session.runtimeEpoch;delete value.session.controlEpoch}this.db.prepare('UPDATE snapshots SET data=? WHERE session_id=? AND runtime=?').run(this.journal.sealSnapshot(streamId,String(row.runtime),value),row.session_id,row.runtime)}this.db.prepare("INSERT INTO host_meta(key,value) VALUES ('snapshot_key_version','session-v1') ON CONFLICT(key) DO UPDATE SET value=excluded.value").run();this.db.exec('COMMIT')}catch(error){this.db.exec('ROLLBACK');throw error}}
  private rebuildUsage(){this.journal.rebuildUsage();this.db.exec("INSERT INTO journal_usage(stream_id,event_bytes,snapshot_bytes,oldest_at) SELECT 'session:'||session_id,0,SUM(length(data)+length(runtime)+length(session_id)+16),NULL FROM snapshots GROUP BY session_id ON CONFLICT(stream_id) DO UPDATE SET snapshot_bytes=excluded.snapshot_bytes")}
  private legacyGeometry(sessionId:string,runtime:string){
    try{const snapshot=this.db.prepare('SELECT data FROM snapshots WHERE session_id=? AND runtime=?').get(sessionId,runtime) as any;if(snapshot){const keyed=!!this.db.prepare("SELECT 1 FROM host_meta WHERE key='snapshot_key_version' AND value='session-v1'").get(),value=keyed?this.journal.openSnapshot<any>(`session:${sessionId}`,runtime,snapshot.data):encrypted(snapshot.data)?this.decode<any>(snapshot.data,`snapshot:${sessionId}:${runtime}`):JSON.parse(snapshot.data);if(Number.isInteger(value?.cols)&&Number.isInteger(value?.rows))return {cols:value.cols,rows:value.rows}}}catch{}
    try{const row=this.db.prepare('SELECT data FROM sessions WHERE id=?').get(sessionId) as any,value=row?this.decode<any>(row.data,`sessions:${sessionId}`):null;if(Number.isInteger(value?.cols)&&Number.isInteger(value?.rows))return {cols:value.cols,rows:value.rows}}catch{}return {cols:100,rows:30};
  }
  private migrateLegacySegments(){
    const segments=this.db.prepare('SELECT * FROM segments ORDER BY session_id,runtime,id').all() as any[],snapshots=this.db.prepare('SELECT session_id,runtime,data FROM snapshots').all() as any[],hooks=this.db.prepare('SELECT * FROM hooks ORDER BY session_id,runtime,at,id').all() as any[],sessionRows=this.db.prepare('SELECT id,data FROM sessions').all() as any[];
    const decodedSessions=new Map<string,any>();try{for(const row of sessionRows)decodedSessions.set(String(row.id),this.decode<any>(row.data,`sessions:${row.id}`))}catch(error){throw new Fault('LEGACY_MIGRATION_FAILED',`旧版会话元数据无法读取：${error instanceof Error?error.message:'invalid data'}`)}for(const row of [...segments,...snapshots,...hooks])if(!decodedSessions.has(String(row.session_id)))throw new Fault('LEGACY_MIGRATION_FAILED',`旧版数据引用了不存在的会话 ${String(row.session_id)}`);
    const runs=new Map<string,{sessionId:string;runtime:string;at:string}>(),addRun=(sessionId:unknown,runtime:unknown,at:unknown)=>{if(typeof runtime!=='string'||!runtime||Number.isSafeInteger(Number(runtime)))return;const key=`${sessionId}\0${runtime}`,timestamp=typeof at==='string'?at:'9999-12-31T23:59:59.999Z',existing=runs.get(key);if(!existing||timestamp<existing.at)runs.set(key,{sessionId:String(sessionId),runtime,at:timestamp})};
    for(const row of segments)addRun(row.session_id,row.runtime,row.at);for(const row of snapshots)addRun(row.session_id,row.runtime,null);for(const row of hooks)addRun(row.session_id,row.runtime,row.at);for(const [id,session]of decodedSessions)addRun(id,session.runtimeEpoch,session.createdAt);
    if(!runs.size)return;
    if(!this.db.prepare("SELECT 1 FROM host_meta WHERE key='legacy_ingest_version' AND value='offset-v2'").get()){
      const entries:any[]=[],hashParts:string[]=[],ordered=[...runs.values()].sort((a,b)=>a.sessionId.localeCompare(b.sessionId)||a.at.localeCompare(b.at)||a.runtime.localeCompare(b.runtime));
      try{for(const run of ordered){
        const streamId=`session:${run.sessionId}`,existing=this.journal.eventsAfter(streamId,0),boundary=existing.find(event=>event.kind==='legacy_runtime_started'&&String((event.payload as any)?.legacyRuntime)===run.runtime),runtimeOffset=boundary?.offset,knownOutput=new Set(existing.filter(event=>event.kind==='pty_output'&&String((event.payload as any)?.legacyRuntime)===run.runtime).map(event=>Number((event.payload as any)?.legacySequence))),knownHooks=new Set(existing.filter(event=>event.actor==='legacy-hook').map(event=>event.operationId));
        if(!boundary)entries.push({streamId,kind:'legacy_runtime_started',at:run.at,payload:{source:'legacy-v1',legacyRuntime:run.runtime,...this.legacyGeometry(run.sessionId,run.runtime)}});
        let lastSequence=0;for(const row of segments.filter(item=>String(item.session_id)===run.sessionId&&String(item.runtime)===run.runtime)){const first=Number(row.first_seq),last=Number(row.last_seq);if(!Number.isSafeInteger(first)||!Number.isSafeInteger(last)||first!==lastSequence+1||last<first)throw new Error(`invalid segment range ${row.id}`);lastSequence=last;if(Array.from({length:last-first+1},(_,index)=>first+index).every(sequence=>knownOutput.has(sequence))){hashParts.push(`existing:${row.id}:${first}:${last}`);continue}if(!existsSync(row.file))throw new Error(`missing segment ${row.id}`);const content=readFileSync(row.file,'utf8'),lines=content.split('\n').filter(Boolean);if(Number(row.size)!==Buffer.byteLength(content)||lines.length!==last-first+1)throw new Error(`invalid segment range ${row.id}`);hashParts.push(`${row.id}:${this.cipher.digest(content)}`);let observed=first-1;for(const line of lines){const item=JSON.parse(line);if(!Number.isSafeInteger(item.seq)||item.seq!==observed+1||typeof item.data!=='string'||typeof item.at!=='string')throw new Error(`invalid segment ${row.id}`);observed=item.seq;if(!knownOutput.has(item.seq))entries.push({streamId,kind:'pty_output',runtimeOffset,at:item.at,payload:{legacySequence:item.seq,data:item.data,at:item.at,legacyRuntime:run.runtime,legacy:true}})}if(observed!==last)throw new Error(`invalid segment range ${row.id}`)}
        for(const hook of hooks.filter(item=>String(item.session_id)===run.sessionId&&String(item.runtime)===run.runtime)){hashParts.push(`hook:${hook.id}:${hook.event}:${hook.at}`);if(knownHooks.has(String(hook.id)))continue;const activity=hook.event==='PermissionRequest'?'approval':hook.event==='Stop'?'done':['SessionStart','Interrupt'].includes(hook.event)?'idle':'working';entries.push({streamId,kind:'agent_state_changed',operationId:String(hook.id),actor:'legacy-hook',runtimeOffset,at:hook.at,payload:{event:hook.event,activity,nativeSessionBound:!!hook.native_id,legacyRuntime:run.runtime,legacy:true}})}
        entries.push({streamId,kind:'legacy_imported',runtimeOffset,payload:{source:'legacy-v1',legacyRuntime:run.runtime}});hashParts.push(`run:${run.sessionId}:${run.runtime}:${snapshots.some(row=>String(row.session_id)===run.sessionId&&String(row.runtime)===run.runtime)}`);
      }}catch(error){throw new Fault('LEGACY_MIGRATION_FAILED',`旧版 journal 无法安全迁移：${error instanceof Error?error.message:'invalid data'}`)}
      this.journal.importLegacy('legacy-v2',this.cipher.eventHash(this.cipher.domainKey,hashParts.join('|')),entries);this.db.prepare("INSERT INTO host_meta(key,value) VALUES ('legacy_ingest_version','offset-v2') ON CONFLICT(key) DO UPDATE SET value=excluded.value").run();
    }
    if(this.db.prepare("SELECT 1 FROM host_meta WHERE key='legacy_projection_version' AND value='offset-v2'").get())return;
    const sessionIds=[...new Set([...runs.values()].map(run=>run.sessionId))];this.db.exec('BEGIN IMMEDIATE');try{
      for(const sessionId of sessionIds){
        const streamId=`session:${sessionId}`,boundaries=this.journal.eventsAfter(streamId,0).filter(event=>event.kind==='legacy_runtime_started');for(const boundary of boundaries)this.db.prepare('INSERT OR REPLACE INTO legacy_runtime_map VALUES (?,?,?)').run(sessionId,String((boundary.payload as any).legacyRuntime),boundary.offset);
        const row=this.db.prepare('SELECT data FROM sessions WHERE id=?').get(sessionId) as any;if(row){const session=this.decode<any>(row.data,`sessions:${sessionId}`),alreadyMapped=boundaries.find(event=>event.offset===session.runtimeOffset),selected=alreadyMapped??boundaries.find(event=>String((event.payload as any).legacyRuntime)===String(session.runtimeEpoch))??boundaries.at(-1);if(selected){session.runtimeOffset=selected.offset;session.controlOffset=null;session.headOffset=this.journal.head(streamId);session.journalState='ready';delete session.runtimeEpoch;delete session.controlEpoch;this.saveSession(session)}}
        for(const snapshot of this.db.prepare('SELECT runtime,data FROM snapshots WHERE session_id=?').all(sessionId) as any[]){const mapped=this.db.prepare('SELECT runtime_offset FROM legacy_runtime_map WHERE session_id=? AND legacy_runtime=?').get(sessionId,String(snapshot.runtime)) as any;if(mapped){const value=encrypted(snapshot.data)?this.decode(snapshot.data,`snapshot:${sessionId}:${snapshot.runtime}`):JSON.parse(snapshot.data),runtime=String(mapped.runtime_offset),data=encrypted(snapshot.data)?this.encode(value,`snapshot:${sessionId}:${runtime}`):JSON.stringify(value);this.db.prepare('INSERT OR REPLACE INTO snapshots VALUES (?,?,?)').run(sessionId,runtime,data);if(runtime!==String(snapshot.runtime))this.db.prepare('DELETE FROM snapshots WHERE session_id=? AND runtime=?').run(sessionId,snapshot.runtime)}}
        for(const table of ['hooks','retention'] as const)for(const item of this.db.prepare(`SELECT rowid,runtime FROM ${table} WHERE session_id=?`).all(sessionId) as any[]){const mapped=this.db.prepare('SELECT runtime_offset FROM legacy_runtime_map WHERE session_id=? AND legacy_runtime=?').get(sessionId,String(item.runtime)) as any;if(mapped)this.db.prepare(`UPDATE ${table} SET runtime=? WHERE rowid=?`).run(String(mapped.runtime_offset),item.rowid)}
      }
      this.db.prepare("INSERT INTO host_meta(key,value) VALUES ('legacy_projection_version','offset-v2') ON CONFLICT(key) DO UPDATE SET value=excluded.value").run();this.db.exec('COMMIT');
    }catch(error){this.db.exec('ROLLBACK');throw error}
  }
  preferences(){const row=this.db.prepare('SELECT data FROM settings WHERE id=1').get() as any;return row?JSON.parse(row.data):{};}
  journalFailureLatched(){const data=readFileSync(this.latchPath);return data.length!==4096||data[0]!==48}
  private writeFailureLatch(failed:boolean){const data=Buffer.alloc(4096);data[0]=failed?49:48;const temporary=`${this.latchPath}.${process.pid}.${randomUUID()}.tmp`;let fd:number|undefined;try{fd=openSync(temporary,'wx',0o600);let written=0;while(written<data.length)written+=writeSync(fd,data,written,data.length-written,written);fsyncSync(fd);closeSync(fd);fd=undefined;renameSync(temporary,this.latchPath);const directory=openSync(this.dir,'r');try{fsyncSync(directory)}finally{closeSync(directory)}}catch(error){if(fd!==undefined)try{closeSync(fd)}catch{}try{unlinkSync(temporary)}catch{}throw error}const verified=readFileSync(this.latchPath);if(verified.length!==data.length||verified[0]!==data[0])throw new Error('Journal health latch verification failed')}
  setJournalFailureLatch(failed:boolean){this.writeFailureLatch(failed)}
  verifyStorage(){const rows=this.db.prepare('PRAGMA quick_check').all() as any[];if(rows.length!==1||Object.values(rows[0]??{})[0]!=='ok')throw new Fault('INTEGRITY_CHECK_FAILED','SQLite 完整性检查失败');this.journal.verify()}
  configure(settings:{preventSleep:boolean;historyDays:number;maxHistoryBytes:number}){this.db.prepare('INSERT INTO settings VALUES (1,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').run(JSON.stringify(settings));this.days=settings.historyDays;this.quota=settings.maxHistoryBytes;}
  projects():Project[]{return (this.db.prepare('SELECT id,data FROM projects ORDER BY rowid').all() as any[]).map(row=>this.decode<Project>(row.data,`projects:${row.id}`))}
  sessions():Session[]{return (this.db.prepare('SELECT id,data FROM sessions ORDER BY rowid DESC').all() as any[]).map(row=>this.decode<Session>(row.data,`sessions:${row.id}`))}
  saveProject(project:Project){this.db.prepare('INSERT INTO projects VALUES (?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').run(project.id,this.encode(project,`projects:${project.id}`))}
  deleteProject(id:string){this.db.prepare('DELETE FROM projects WHERE id=?').run(id)}
  saveSession(session:Session){this.db.prepare('INSERT INTO sessions VALUES (?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').run(session.id,this.encode(session,`sessions:${session.id}`))}
  deleteSessionWithin(id:string){const streamId=`session:${id}`;for(const row of this.db.prepare('SELECT file FROM segments WHERE session_id=?').all(id) as any[]){const deletionId=this.cipher.eventHash(this.cipher.domainKey,String(row.file));this.db.prepare('INSERT OR IGNORE INTO pending_file_deletions VALUES (?,?)').run(deletionId,this.encode({path:String(row.file)},`pending-file:${deletionId}`))}this.db.prepare('DELETE FROM legacy_backups WHERE session_id=?').run(id);this.db.prepare('DELETE FROM segments WHERE session_id=?').run(id);this.db.prepare('DELETE FROM legacy_runtime_map WHERE session_id=?').run(id);this.db.prepare('DELETE FROM snapshots WHERE session_id=?').run(id);this.db.prepare('DELETE FROM hooks WHERE session_id=?').run(id);this.db.prepare('DELETE FROM retention WHERE session_id=?').run(id);this.db.prepare('DELETE FROM journal_operations WHERE stream_id=?').run(streamId);this.db.prepare('DELETE FROM journal_events WHERE stream_id=?').run(streamId);this.db.prepare('DELETE FROM session_keys WHERE stream_id=?').run(streamId);this.db.prepare('DELETE FROM journal_streams WHERE stream_id=?').run(streamId);this.db.prepare('DELETE FROM journal_usage WHERE stream_id=?').run(streamId);this.db.prepare('DELETE FROM journal_runtime_runs WHERE stream_id=?').run(streamId);this.db.prepare('DELETE FROM sessions WHERE id=?').run(id)}
  cleanupPendingFiles(){const root=realpathSync(join(this.dir,'logs'));for(const row of this.db.prepare('SELECT id,data FROM pending_file_deletions').all() as any[])try{const {path}=this.decode<{path:string}>(row.data,`pending-file:${row.id}`),parent=realpathSync(dirname(path)),parentRel=relative(root,parent);if(parentRel.startsWith('..')||isAbsolute(parentRel))continue;let missing=false;try{lstatSync(path)}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')missing=true;else throw error}if(!missing){const target=realpathSync(path),rel=relative(root,target);if(!rel||rel.startsWith('..')||isAbsolute(rel))continue;unlinkSync(path);this.cleanupFaults?.hit('delete.afterUnlink')}const fd=openSync(parent,'r');try{fsyncSync(fd)}finally{closeSync(fd)}this.db.exec('BEGIN IMMEDIATE');try{this.db.prepare('DELETE FROM pending_file_deletions WHERE id=?').run(row.id);this.db.exec('COMMIT')}catch(error){this.db.exec('ROLLBACK');throw error}}catch{/* Keep the encrypted cleanup record for the next startup. */}}
  saveOffsetSnapshot(snapshot:SessionSnapshot){const runtime=String(snapshot.session.runtimeOffset??0),streamId=`session:${snapshot.session.id}`,data=this.journal.sealSnapshot(streamId,runtime,snapshot),previous=this.db.prepare('SELECT length(data) bytes FROM snapshots WHERE session_id=? AND runtime=?').get(snapshot.session.id,runtime) as any,delta=Buffer.byteLength(data)-Number(previous?.bytes??0)+(previous?0:Buffer.byteLength(runtime)+Buffer.byteLength(snapshot.session.id)+16);this.db.exec('BEGIN IMMEDIATE');try{this.db.prepare('INSERT INTO snapshots VALUES (?,?,?) ON CONFLICT(session_id,runtime) DO UPDATE SET data=excluded.data').run(snapshot.session.id,runtime,data);this.db.prepare('INSERT INTO journal_usage(stream_id,event_bytes,snapshot_bytes) VALUES (?,0,?) ON CONFLICT(stream_id) DO UPDATE SET snapshot_bytes=MAX(0,journal_usage.snapshot_bytes+excluded.snapshot_bytes)').run(streamId,delta);this.db.exec('COMMIT')}catch(error){this.db.exec('ROLLBACK');throw error}}
  offsetSnapshot(id:string,runtimeOffset:number):SessionSnapshot|null{const runtime=String(runtimeOffset),row=this.db.prepare('SELECT data FROM snapshots WHERE session_id=? AND runtime=?').get(id,runtime) as any;if(!row)return null;try{return this.journal.openSnapshot<SessionSnapshot>(`session:${id}`,runtime,row.data)}catch{throw new Fault('SNAPSHOT_CORRUPT','保存的终端快照已损坏，可从 journal 重新构建')}}
  recordHook(id:string,session:Session,event:string,at:string,nativeId=session.nativeSessionId){const encoded=nativeId?this.encode(nativeId,`hook:${id}`):null;const result=this.db.prepare('INSERT OR IGNORE INTO hooks VALUES (?,?,?,?,?,?)').run(id,session.id,String(session.runtimeOffset),event,encoded,at);return result.changes>0}
  hasHook(id:string){return !!this.db.prepare('SELECT 1 FROM hooks WHERE id=?').get(id)}
  prune(){/* Journal history is permanent until an explicit user deletion. */}
  storageUsage(){
    const sessions:Record<string,number>={};for(const row of this.db.prepare("SELECT substr(stream_id,9) session_id,event_bytes+snapshot_bytes bytes FROM journal_usage WHERE stream_id LIKE 'session:%'").all() as any[])sessions[row.session_id]=Number(row.bytes);
    const database=join(this.dir,'host.sqlite');let totalBytes=0;for(const file of [database,`${database}-wal`,`${database}-shm`])try{totalBytes+=statSync(file).size}catch{}
    const oldest=this.db.prepare("SELECT MIN(oldest_at) oldest_at FROM journal_usage WHERE stream_id LIKE 'session:%'").get() as any,oldestAt=typeof oldest?.oldest_at==='string'?oldest.oldest_at:null;
    const age=oldestAt?Date.now()-Date.parse(oldestAt):0,warning=totalBytes>=this.quota*.8||age>=this.days*86_400_000*.8;
    return {totalBytes,warning,maxHistoryBytes:this.quota,historyDays:this.days,oldestAt,sessions};
  }
  history(id:string,runtimeOffset:number,before=Number.MAX_SAFE_INTEGER,limit=100,runBefore=Number.MAX_SAFE_INTEGER,runLimit=200){
    const streamId=`session:${id}`,page=this.journal.eventsBeforeByKind(streamId,'pty_output',runtimeOffset,before,limit),runPage=this.journal.runtimeRuns(streamId,runBefore,runLimit);
    return {entries:page.events.map(event=>{const payload=event.payload as any;return {offset:event.offset,data:String(payload?.data??''),at:String(payload?.at??event.at)}}),hasMore:page.hasMore,truncated:false,runtimeOffset,runs:runPage.runs,runsHasMore:runPage.hasMore};
  }
  close(){this.db.close()}
}
