import {test,expect,type Page} from '@playwright/test';
import {accept,identityFingerprint,testIdentity} from './channel-fixture.ts';

const session={id:'s1',hostId:'h1',projectId:'p1',title:'真实终端测试',agent:'codex',processState:'running',activity:'idle',nativeSessionId:null,controller:null,cols:90,rows:30,createdAt:'2026-09-08T10:00:00Z',updatedAt:'2026-09-08T10:00:00Z',archived:false,runtimeOffset:2,controlOffset:null,headOffset:2,journalState:'ready'};
const project={id:'p1',hostId:'h1',name:'example',path:'/Users/test/Projects/example',createdAt:session.createdAt};
const host={id:'h1',name:'测试主机',online:true,platform:'darwin',roots:['/Users/test/Projects'],settings:{preventSleep:false,historyDays:30,maxHistoryBytes:134217728},storage:{totalBytes:1572864,warning:false,maxHistoryBytes:134217728,historyDays:30,oldestAt:'2026-09-11T00:00:00.000Z'},agents:[{id:'codex',name:'Codex',available:true,path:'/usr/bin/codex',version:'test'},{id:'claude',name:'Claude Code',available:false,path:null,version:null,reason:'尚未安装'}]};

async function authRoutes(page:Page,hosts=[host]){
 await page.route('**/api/auth',route=>route.fulfill({json:{authenticated:true,user:{id:'u1',name:'测试用户'},csrfToken:'csrf-test',mode:'development'}}));
 await page.route('**/api/hosts',route=>route.fulfill({json:{hosts}}));
 await page.route('**/api/browsers',route=>route.fulfill({json:{browsers:[{id:'current-login',createdAt:1788900000000,expiresAt:1789900000000,current:true},{id:'other-login',createdAt:1788800000000,expiresAt:1789800000000,current:false}]}}));
}

async function setup(page:Page){
 let state:any={...session},socket:any,server:any,clientId='',offset=2,manyHistory=false;const calls:{method:string;params:any}[]=[],facts:any[]=[],identity=testIdentity();
 await authRoutes(page);await page.addInitScript(fingerprint=>localStorage.setItem('polyhedron.host-fingerprint.h1',fingerprint),identityFingerprint(identity));
 const sendEvent=(event:any)=>socket.send(JSON.stringify({type:'sealed_event',hostId:'h1',channelId:server.hello.channelId,cipher:server.channel.seal({...event,hostId:'h1',clientId,channelId:server.hello.channelId})}));
 const fact=(kind:string,extra:any={})=>{offset++;state={...state,headOffset:offset};const event={type:'event',event:'journal',kind,sessionId:'s1',offset,runtimeOffset:state.runtimeOffset,...extra};facts.push(event);sendEvent(event);return offset};
 await page.routeWebSocket('**/ws/browser?*',ws=>{socket=ws;clientId=new URL(ws.url()).searchParams.get('clientId')!;ws.onMessage(raw=>{void(async()=>{const envelope=JSON.parse(String(raw));if(envelope.type==='open_channel'){server=accept(identity,{v:1,hostId:'h1',channelId:envelope.channelId,clientPublicKey:envelope.clientPublicKey});ws.send(JSON.stringify({type:'channel_opened',id:envelope.id,hostId:'h1',channelId:envelope.channelId,hello:server.hello}));return}if(envelope.type!=='sealed')return;const request=server.channel.open(envelope.cipher);calls.push({method:request.method,params:request.params});const reply=(result:any,error?:any)=>ws.send(JSON.stringify({type:'sealed_result',id:envelope.id,hostId:'h1',channelId:envelope.channelId,cipher:server.channel.seal({type:'response',id:request.id,...(error?{error}:{result})})}));switch(request.method){
    case 'list':reply({host,projects:[project],sessions:[state]});break;
    case 'attach':{const snapshot={session:{...state},baseOffset:2,headOffset:offset,data:'SNAPSHOT_CONTENT\r\n',cols:90,rows:30,events:Array.from({length:offset-2},(_,index)=>({type:'event',event:'journal',kind:'operation_applied',hostId:'h1',sessionId:'s1',offset:index+3,runtimeOffset:2,session:{...state}}))};fact('pty_output',{data:'LIVE_AFTER_SNAPSHOT\r\n'});reply(snapshot);break}
    case 'claimControl':fact('control_requested',{session:{...state}});state={...state,controller:server.hello.channelId,controlOffset:offset+1};fact('control_acquired',{session:{...state}});reply(state);break;
    case 'resize':state={...state,cols:request.params.cols,rows:request.params.rows};fact('resize_requested',{session:{...state}});fact('resize_applied',{session:{...state}});sendEvent({type:'event',event:'snapshot',sessionId:'s1',session:{...state},baseOffset:2,headOffset:offset,data:'SNAPSHOT_CONTENT\r\n',cols:state.cols,rows:state.rows,events:facts.map(event=>({...event,session:event.session??{...state}}))});reply(state);break;
    case 'history':{const runtimeOffset=request.params.runtimeOffset??state.runtimeOffset,runs=manyHistory?(request.params.runBefore?[{runtimeOffset:1,createdAt:'2026-01-01T00:00:00Z'}]:[{runtimeOffset:2,createdAt:session.createdAt},...Array.from({length:199},(_,index)=>({runtimeOffset:400-index,createdAt:'2026-09-07T10:00:00Z'}))]):[{runtimeOffset:2,createdAt:session.createdAt},{runtimeOffset:1,createdAt:'2026-09-07T10:00:00Z'}];reply({runs,runsHasMore:manyHistory&&!request.params.runBefore,entries:[{offset:1,data:runtimeOffset===1?'PREVIOUS_RUN':'HISTORY_ONLY\x1b[31m',at:session.createdAt}],hasMore:false,truncated:false,runtimeOffset});break}
    case 'listDirectories':{const path=request.params.path;reply(path===undefined?{path:null,parent:null,entries:[{name:'Projects',path:'/Users/test/Projects'}]}:path==='/Users/test/Projects'?{path,parent:null,entries:[{name:'我的应用',path:path+'/我的应用'}]}:{path,parent:'/Users/test/Projects',entries:[]});break}
    case 'addProject':reply({...project,id:'p2',name:request.params.name,path:request.params.path});break;
    case 'configureHost':reply(request.params);break;
    case 'input':fact('input_requested',{session:{...state}});fact('input_applied',{session:{...state}});reply({accepted:true});break;
    default:reply({ok:true});
   }})()})});
 await page.goto('/');await page.getByRole('button',{name:/真实终端测试/}).click();await expect(page.getByRole('status').filter({hasText:'只读'})).toBeVisible();
 return {calls,manyRuns(){manyHistory=true},screen(data:string){sendEvent({type:'event',event:'snapshot',sessionId:'s1',session:{...state},baseOffset:offset,headOffset:offset,data,cols:90,rows:30,events:[]})},query(){fact('pty_output',{data:'\x1b[6n\x1b[c\x1b[>c\x1b]52;c;dGVzdA==\x07QUERY_END'})},broadcastSnapshot(){sendEvent({type:'event',event:'snapshot',sessionId:'s1',session:{...state},baseOffset:offset,headOffset:offset,data:'RESIZED_SNAPSHOT\r\n',cols:72,rows:24,events:[]})},resync(){sendEvent({type:'event',event:'resync',sessionId:'s1'})},revoke(){state={...state,controller:'another-channel',controlOffset:offset+1};fact('control_acquired',{session:{...state}})},journalFailure(){state={...state,journalState:'unavailable',warning:'本地 journal 写入失败'};fact('journal_degraded',{session:{...state}})},disconnect(){socket.close()}};
}
async function setupEmptyWorkspace(page:Page,trusted=true){await authRoutes(page);const identity=testIdentity();let listRequests=0;if(trusted)await page.addInitScript(fingerprint=>localStorage.setItem('polyhedron.host-fingerprint.h1',fingerprint),identityFingerprint(identity));await page.routeWebSocket('**/ws/browser?*',ws=>{let server:any;ws.onMessage(raw=>{const envelope=JSON.parse(String(raw));if(envelope.type==='open_channel'){server=accept(identity,{v:1,hostId:'h1',channelId:envelope.channelId,clientPublicKey:envelope.clientPublicKey});ws.send(JSON.stringify({type:'channel_opened',id:envelope.id,hostId:'h1',channelId:envelope.channelId,hello:server.hello}));return}const request=server.channel.open(envelope.cipher),result=request.method==='list'?{host,projects:[],sessions:[]}:{ok:true};if(request.method==='list')listRequests++;ws.send(JSON.stringify({type:'sealed_result',id:envelope.id,hostId:'h1',channelId:envelope.channelId,cipher:server.channel.seal({type:'response',id:request.id,result})}))})});await page.goto('/');return {listRequests:()=>listRequests}}
async function setupOfflineWorkspace(page:Page){await authRoutes(page,[{...host,online:false}]);await page.routeWebSocket('**/ws/browser?*',()=>{});await page.goto('/')}

test('snapshot and live offsets render in order; input stays blocked until claim and resize, then revocation blocks it',async({page})=>{
 const {calls,revoke}=await setup(page);await expect.poll(()=>calls.filter(call=>call.method==='eventAck').map(call=>call.params.appliedOffset)).toContain(3);expect(calls.some(call=>call.method==='claimControl')).toBe(false);
 await page.locator('.xterm-helper-textarea').focus();await page.keyboard.type('blocked');expect(calls.filter(call=>call.method==='input')).toHaveLength(0);
 await page.getByRole('button',{name:'会话详情',exact:true}).click();await page.getByRole('button',{name:'接管控制',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'已接管'})).toBeVisible();await page.locator('.xterm-helper-textarea').focus();await page.keyboard.type('x');await expect.poll(()=>calls.filter(call=>call.method==='input').length).toBe(1);
 const input=calls.find(call=>call.method==='input')!;expect(input.params).toMatchObject({runtimeOffset:2,data:'x'});expect(input.params.controlOffset).toBeGreaterThan(2);expect(input.params.inputSeq).toBeUndefined();expect(typeof input.params.operationId).toBe('string');expect(calls.findIndex(call=>call.method==='resize')).toBeLessThan(calls.findIndex(call=>call.method==='input'));
 revoke();await expect(page.getByRole('status').filter({hasText:'只读'})).toBeVisible();await page.keyboard.type('blocked');expect(calls.filter(call=>call.method==='input')).toHaveLength(1);
});
test('six palettes, project scoped creation, unavailable agent and Host-backed read-only history',async({page})=>{
 const {calls}=await setup(page);await page.getByRole('button',{name:'设置',exact:true}).click();for(const name of ['电光蓝','鸢尾紫','珊瑚橙','翡翠绿','玫瑰粉','原版蓝青']){const button=page.getByRole('button',{name:new RegExp(name)});await button.click();await expect(button).toHaveAttribute('aria-pressed','true')}await page.getByLabel('终端字号').fill('18');await expect(page.getByText('18px',{exact:true})).toBeVisible();await page.getByRole('button',{name:'关闭对话框'}).click();
 await page.locator('.project-group').filter({hasText:'example'}).hover();await page.getByRole('button',{name:'在 example 中新建会话',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('/Users/test/Projects/example');await expect(page.getByRole('radio',{name:/Claude Code/})).toBeDisabled();await page.getByRole('button',{name:'关闭对话框'}).click();await page.getByRole('button',{name:'会话详情',exact:true}).click();await page.getByRole('button',{name:'历史记录',exact:true}).click();await expect(page.locator('.history-output')).toHaveText('HISTORY_ONLY');await page.getByLabel('选择历史运行').selectOption('1');await expect(page.locator('.history-output')).toHaveText('PREVIOUS_RUN');expect(calls.filter(call=>call.method==='input')).toHaveLength(0);await page.getByRole('button',{name:'关闭对话框'}).click();await page.getByRole('button',{name:'进入专注模式'}).click();await expect(page.getByRole('complementary')).toBeHidden();await page.keyboard.press('Control+k');await expect(page.getByRole('searchbox',{name:'搜索会话或项目'})).toBeFocused();
});
test('history keeps a selected runtime after loading beyond the first 200 runs',async({page})=>{const {manyRuns}=await setup(page);manyRuns();await page.getByRole('button',{name:'会话详情',exact:true}).click();await page.getByRole('button',{name:'历史记录',exact:true}).click();await page.getByRole('button',{name:'加载更早运行',exact:true}).click();await page.getByLabel('选择历史运行').selectOption('1');await expect(page.getByLabel('选择历史运行')).toHaveValue('1');await expect(page.locator('.history-output')).toHaveText('PREVIOUS_RUN')});
test('disconnect suspends input and reconnect requires a fresh encrypted channel, snapshot and explicit claim',async({page})=>{const {calls,disconnect}=await setup(page);await page.getByRole('button',{name:'会话详情',exact:true}).click();await page.getByRole('button',{name:'接管控制',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'已接管'})).toBeVisible();disconnect();await expect.poll(()=>calls.filter(call=>call.method==='attach').length).toBe(2);await expect(page.getByRole('status').filter({hasText:'只读'})).toBeVisible();await page.locator('.xterm-helper-textarea').focus();await page.keyboard.type('never-replay');expect(calls.filter(call=>call.method==='input')).toHaveLength(0);expect(calls.filter(call=>call.method==='claimControl')).toHaveLength(1)});
test('authoritative snapshots preserve readonly viewing and resync reattaches without claiming',async({page})=>{const {calls,broadcastSnapshot,resync}=await setup(page);broadcastSnapshot();await page.getByRole('button',{name:'搜索终端',exact:true}).click();await page.getByRole('searchbox',{name:'在终端中查找'}).fill('RESIZED_SNAPSHOT');await page.getByRole('button',{name:'下一个',exact:true}).click();await expect(page.locator('.toast')).toHaveCount(0);expect(calls.filter(call=>call.method==='resize')).toHaveLength(0);expect(calls.filter(call=>call.method==='claimControl')).toHaveLength(0);resync();await expect.poll(()=>calls.filter(call=>call.method==='attach').length).toBe(2);await expect(page.getByRole('status').filter({hasText:'只读'})).toBeVisible()});
test('journal failure disables history and control with a visible explanation',async({page})=>{const {journalFailure}=await setup(page);journalFailure();await expect(page.getByRole('status').filter({hasText:'本地会话记录不可用'})).toBeVisible();await page.getByRole('button',{name:'会话详情',exact:true}).click();await expect(page.getByRole('button',{name:'接管控制',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'历史记录',exact:true})).toBeDisabled()});
test('keyboard project search has a visible focus indicator',async({page})=>{await setup(page);await page.keyboard.press('Control+k');await expect(page.getByRole('searchbox',{name:'搜索会话或项目'})).toBeFocused();await expect(page.locator('.session-search')).toHaveCSS('border-color','rgb(141, 173, 255)')});
test('terminal search has a visible focus indicator',async({page})=>{await setup(page);await page.getByRole('button',{name:'搜索终端',exact:true}).click();await expect(page.getByRole('searchbox',{name:'在终端中查找'})).toBeFocused();await expect(page.locator('.terminal-search')).toHaveCSS('border-color','rgb(154, 186, 255)')});
test('the application keeps one stable page heading',async({page})=>{await setupEmptyWorkspace(page);await expect(page.getByRole('heading',{name:'多面体',level:1,exact:true})).toHaveCount(1);await expect(page.getByRole('heading',{level:1})).toHaveCount(1);await page.setViewportSize({width:390,height:844});await expect(page.getByRole('heading',{name:'多面体',level:1,exact:true})).toHaveCount(1)});
test('first Host use requires explicit trust and immediately reloads Host state',async({page})=>{const observed=await setupEmptyWorkspace(page,false);const dialog=page.getByRole('dialog',{name:'确认执行主机身份'});await expect(dialog).toBeVisible();await expect(dialog.locator('.trust-fingerprint')).toHaveText(/^[A-Za-z0-9_-]{43}$/);await dialog.getByRole('button',{name:'我已核对并信任此主机'}).click();await expect(dialog).toHaveCount(0);await expect.poll(()=>page.evaluate(()=>localStorage.getItem('polyhedron.host-fingerprint.h1'))).toMatch(/^[A-Za-z0-9_-]{43}$/);await expect.poll(observed.listRequests,{timeout:10_000}).toBe(1)});
test('mobile header keeps the product identity visible',async({page})=>{await setupEmptyWorkspace(page);await page.setViewportSize({width:390,height:844});const heading=page.getByRole('heading',{name:'多面体',level:1,exact:true});await expect(heading).toBeVisible();expect((await heading.boundingBox())!.width).toBeGreaterThan(30)});
test('the skip link moves keyboard focus to the terminal workspace',async({page})=>{await setup(page);const skip=page.getByRole('link',{name:'跳到会话工作区',exact:true});await skip.focus();await page.keyboard.press('Enter');await expect(page.locator('#terminal-workspace')).toBeFocused()});
test('mobile icon controls keep usable touch targets',async({page})=>{await setup(page);await page.setViewportSize({width:390,height:844});const add=await page.getByRole('button',{name:'添加项目',exact:true}).boundingBox(),search=await page.getByRole('button',{name:'搜索终端',exact:true}).boundingBox();expect(add!.width).toBeGreaterThanOrEqual(36);expect(add!.height).toBeGreaterThanOrEqual(36);expect(search!.width).toBeGreaterThanOrEqual(36);expect(search!.height).toBeGreaterThanOrEqual(36);await expect(page.getByRole('button',{name:'搜索终端',exact:true})).toHaveCSS('touch-action','manipulation')});
test('online host without projects offers a usable first-project action',async({page})=>{await setupEmptyWorkspace(page);await expect(page.getByText('点击左侧 Projects 旁的“添加项目”，创建第一个项目。',{exact:true})).toBeVisible();await page.getByRole('button',{name:'添加第一个项目',exact:true}).click();await expect(page.getByRole('dialog',{name:'添加项目'})).toBeVisible()});
test('offline host exposes no cached sessions and settings contain their own scroll',async({page})=>{await setupOfflineWorkspace(page);await expect(page.getByRole('button',{name:/真实终端测试/})).toHaveCount(0);await page.getByRole('button',{name:'设置',exact:true}).click();const dialog=page.getByRole('dialog',{name:'设置'});await expect(dialog).toHaveCSS('overscroll-behavior-y','contain');await expect(dialog.getByText('离线',{exact:true})).toHaveCSS('color','rgb(141, 154, 177)')});
test('liquid glass shell keeps navigation beside terminal and details float above it',async({page},testInfo)=>{const browserErrors:string[]=[];page.on('pageerror',error=>browserErrors.push(error.message));page.on('console',message=>{if(message.type()==='error')browserErrors.push(message.text())});await setup(page);await expect(page.locator('.shell-header')).toBeVisible();await expect(page.locator('#command-form')).toHaveCount(0);await expect(page.locator('.xterm-helper-textarea')).toHaveCount(1);await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight)).toBe(true);const sidebar=await page.locator('.sidebar').boundingBox(),workspace=await page.locator('.workspace-card').boundingBox();expect(Math.abs(sidebar!.y-workspace!.y)).toBeLessThan(2);expect(workspace!.x).toBeGreaterThan(sidebar!.x+sidebar!.width-1);const width=workspace!.width;await page.getByRole('button',{name:'会话详情',exact:true}).click();await expect(page.locator('.session-details-sheet')).toBeVisible();expect((await page.locator('.workspace-card').boundingBox())?.width).toBe(width);await page.screenshot({path:testInfo.outputPath('desktop.png'),fullPage:true});await page.setViewportSize({width:736,height:863});const compactSidebar=await page.locator('.sidebar').boundingBox(),compactWorkspace=await page.locator('.workspace-card').boundingBox();expect(Math.abs(compactSidebar!.y-compactWorkspace!.y)).toBeLessThan(2);expect(compactWorkspace!.x).toBeGreaterThan(compactSidebar!.x+compactSidebar!.width-1);await page.getByRole('button',{name:'设置',exact:true}).click();await page.screenshot({path:testInfo.outputPath('settings.png'),fullPage:true});await page.getByRole('button',{name:'关闭对话框'}).click();await page.setViewportSize({width:580,height:844});const thresholdSidebar=await page.locator('.sidebar').boundingBox(),thresholdWorkspace=await page.locator('.workspace-card').boundingBox();expect(thresholdWorkspace!.x).toBeGreaterThan(thresholdSidebar!.x+thresholdSidebar!.width-1);await page.getByRole('button',{name:'设置',exact:true}).click();await page.setViewportSize({width:390,height:844});await expect(page.getByRole('dialog')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);expect(browserErrors).toEqual([])});
test('display queries never become controller input and OSC52 cannot write clipboard',async({page})=>{const {calls,query}=await setup(page);await page.getByRole('button',{name:'会话详情',exact:true}).click();await page.getByRole('button',{name:'接管控制',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'已接管'})).toBeVisible();query();await expect.poll(()=>calls.filter(call=>call.method==='eventAck').map(call=>call.params.appliedOffset)).toContain(8);expect(calls.filter(call=>call.method==='input')).toHaveLength(0);await page.locator('.xterm-helper-textarea').focus();await page.keyboard.type('y');await expect.poll(()=>calls.filter(call=>call.method==='input').length).toBe(1);expect(calls.find(call=>call.method==='input')?.params.data).toBe('y')});
test('expired development authentication returns to development login',async({page})=>{const {disconnect}=await setup(page);await page.route('**/api/auth',route=>route.fulfill({json:{authenticated:false,mode:'development'}}));await page.route('**/api/hosts',route=>route.fulfill({status:401,json:{error:{code:'UNAUTHENTICATED',message:'Session expired'}}}));disconnect();await expect(page.getByRole('button',{name:'进入本机工作台'})).toBeVisible();await expect(page.getByRole('link',{name:'登录并继续'})).toHaveCount(0)});
test('host preferences submit bounded warning settings and idle sessions appear pending',async({page})=>{const {calls}=await setup(page);await page.getByRole('button',{name:/^待处理/}).click();await expect(page.getByRole('button',{name:/真实终端测试/})).toBeVisible();await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByLabel('任务运行时阻止空闲睡眠').check();await page.getByLabel('历史告警周期（天）').fill('45');await page.getByLabel('历史告警容量（MiB）').fill('256');await page.getByRole('button',{name:'保存主机设置'}).click();await expect.poll(()=>calls.find(call=>call.method==='configureHost')?.params).toMatchObject({preventSleep:true,historyDays:45,maxHistoryBytes:268435456})});
test('other browser login revocation requires confirmation and sends CSRF',async({page})=>{await setup(page);let revoked=false;await page.route('**/api/browsers/other-login/revoke',route=>{expect(route.request().headers()['x-csrf-token']).toBe('csrf-test');revoked=true;return route.fulfill({json:{ok:true}})});await page.getByRole('button',{name:'设置',exact:true}).click();await expect(page.getByText('当前登录',{exact:true})).toBeVisible();await page.getByRole('button',{name:'撤销登录',exact:true}).click();expect(revoked).toBe(false);await page.getByRole('button',{name:'确认',exact:true}).click();await expect.poll(()=>revoked).toBe(true)});
test('folder picker browses directories, preserves cancellation and submits chosen path',async({page})=>{const {calls}=await setup(page);await page.getByRole('button',{name:'添加项目',exact:true}).click();await page.getByRole('button',{name:'选择文件夹',exact:true}).click();await expect(page.getByRole('dialog',{name:'选择项目文件夹'})).toBeVisible();await page.getByRole('button',{name:'打开 Projects',exact:true}).click();await page.getByRole('button',{name:'打开 我的应用',exact:true}).click();await expect(page.getByText('此文件夹内没有可浏览的子文件夹。')).toBeVisible();await page.getByRole('button',{name:'选择此文件夹',exact:true}).click();await expect(page.getByLabel('项目目录',{exact:true})).toHaveValue('/Users/test/Projects/我的应用');await expect(page.getByLabel('项目名称',{exact:true})).toHaveValue('我的应用');await page.getByLabel('项目名称',{exact:true}).fill('自定义项目');await page.getByRole('button',{name:'选择文件夹',exact:true}).click();await page.getByRole('button',{name:'上一级',exact:true}).click();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(1);await expect(page.getByLabel('项目目录',{exact:true})).toHaveValue('/Users/test/Projects/我的应用');await expect(page.getByLabel('项目名称',{exact:true})).toHaveValue('自定义项目');await page.getByRole('button',{name:'添加项目',exact:true}).last().click();await expect.poll(()=>calls.find(call=>call.method==='addProject')?.params).toMatchObject({name:'自定义项目',path:'/Users/test/Projects/我的应用'})});
test('project header exposes scoped create and settings controls on hover or focus',async({page},testInfo)=>{await setup(page);const group=page.locator('.project-group').filter({hasText:'example'}),actions=group.locator('.project-actions'),create=group.getByRole('button',{name:'在 example 中新建会话',exact:true}),settings=group.getByRole('button',{name:'example 项目设置',exact:true});await page.getByRole('button',{name:'全部会话 1',exact:true}).focus();await page.mouse.move(600,100);await expect(actions).toHaveCSS('opacity','0');await group.hover();await expect(actions).toHaveCSS('opacity','1');await create.click();await expect(page.getByRole('dialog',{name:'新建会话'})).toContainText('/Users/test/Projects/example');await page.getByRole('button',{name:'关闭对话框'}).click();await settings.focus();await expect(actions).toHaveCSS('opacity','1');await settings.click();await expect(page.getByRole('dialog',{name:'项目设置'})).toBeVisible();await page.screenshot({path:testInfo.outputPath('project-actions.png')})});
test('native user prompt backgrounds follow repaint without forwarding input',async({page},testInfo)=>{const {screen,calls}=await setup(page);screen('› 帮我检查登录流程\r\n模型输出保持原生样式\r\n> 引用文字不算用户输入');await expect(page.locator('.terminal-input-row')).toHaveCount(1);await expect(page.locator('.terminal-input-row')).toHaveCSS('pointer-events','none');await expect(page.locator('.xterm-accessibility-tree')).toContainText('模型输出保持原生样式');expect(calls.filter(call=>call.method==='input')).toHaveLength(0);await page.screenshot({path:testInfo.outputPath('terminal-input-contrast.png')});screen('模型的新输出\r\n没有用户提示行');await expect(page.locator('.terminal-input-row')).toHaveCount(0);screen('\x1b[?1049h› 全屏终端输入\r\n全屏输出');await expect(page.locator('.terminal-input-row')).toHaveCount(1);screen('\x1b[?1049l普通终端输出');await expect(page.locator('.terminal-input-row')).toHaveCount(0)});
