import {useCallback,useEffect,useMemo,useRef,useState,type FormEvent} from 'react';
import {http,RpcClient,ApiError,type Connection} from './api';
import {agentName,type Auth,type BrowserLogin,type State,type Session,type Project,type Host,type HostSettings,type Agent,type History} from './types';
import type {TerminalActions} from './TerminalView';
import {ProjectForm} from './ProjectForm';
import {Icon} from './components/Icon';
import {Field,Modal} from './components/Modal';
import {ShellHeader} from './components/ShellHeader';
import {Sidebar,type SessionFilter} from './components/Sidebar';
import {Workspace} from './components/Workspace';
const empty:State={hosts:[],projects:[],sessions:[]};
const palettes=[['electric','电光蓝','清亮 · 科技'],['iris','鸢尾紫','灵感 · 创作'],['coral','珊瑚橙','温暖 · 活力'],['emerald','翡翠绿','清新 · 轻快'],['rose','玫瑰粉','明快 · 个性'],['original','原版蓝青','柔和 · 克制']];
function saved(key:string,fallback:string){try{return localStorage.getItem(key)||fallback}catch{return fallback}}
function savedCompletions():Record<string,string>{try{const value=JSON.parse(saved('polyhedron.seenCompletions','{}'));return value&&typeof value==='object'&&!Array.isArray(value)?value:{}}catch{return {}}}
function storePreference(key:string,value:string){try{localStorage.setItem(key,value)}catch{/* Preferences remain available for this page. */}}
function date(value:string|number){const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString('zh-CN')}
function cleanHistory(text:string){return text.replace(/\x1b\][^\x07]*(?:\x07|\x1b\\)/g,'').replace(/\x1b\[[0-?]*[ -/]*[@-~]/g,'').replace(/\x1b[@-_]/g,'').replace(/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/g,'')}
type Dialog = {kind:'settings'|'help'|'project'}|{kind:'new';project:Project}|{kind:'renameSession';session:Session}|{kind:'editProject';project:Project}|{kind:'history';session:Session}|{kind:'confirm';title:string;description:string;action:()=>Promise<unknown>};
export default function App(){
 const [browsers,setBrowsers]=useState<BrowserLogin[]|null>(null),[browserError,setBrowserError]=useState('');
 const [seenCompletions,setSeenCompletions]=useState<Record<string,string>>(savedCompletions);
 const [auth,setAuth]=useState<Auth|null>(null),[authError,setAuthError]=useState(''),[data,setData]=useState<State>(empty),[loaded,setLoaded]=useState(false),[connection,setConnection]=useState<Connection>('offline');
 const [terminalVersion,setTerminalVersion]=useState(0);const [selected,setSelected]=useState<string|null>(null),[filter,setFilter]=useState<SessionFilter>('all'),[query,setQuery]=useState(''),[collapsed,setCollapsed]=useState<Set<string>>(new Set()),[details,setDetails]=useState(false),[focus,setFocus]=useState(false),[dialog,setDialog]=useState<Dialog|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState(''),[conflict,setConflict]=useState(false);
 const [palette,setPalette]=useState(()=>{const p=new URLSearchParams(location.search).get('palette')||saved('polyhedron.palette','electric');return palettes.some(x=>x[0]===p)?p:'electric'}),[fontSize,setFontSize]=useState(()=>Math.min(20,Math.max(12,Number(saved('polyhedron.fontSize','14'))||14))),[searchOpen,setSearchOpen]=useState(false),[terminalQuery,setTerminalQuery]=useState('');
 const [history,setHistory]=useState<History|null>(null),[historyLoading,setHistoryLoading]=useState(false);const historySession=useRef<string|null>(null),historyRequest=useRef(0);
 const rpc=useMemo(()=>new RpcClient(),[]),terminal=useRef<TerminalActions>(null),searchInput=useRef<HTMLInputElement>(null),refreshTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 const notify=useCallback((message:string)=>setToast(message),[]);
 const updateSession=useCallback((s:Session)=>setData(old=>({...old,sessions:old.sessions.some(x=>x.id===s.id)?old.sessions.map(x=>x.id===s.id?s:x):[s,...old.sessions]})),[]);
 const refresh=useCallback(async()=>{try{const next=await http<State>('/api/state');setData(old=>{const online=new Set(next.hosts.filter(x=>x.online).map(x=>x.id)),known=new Set(next.hosts.map(x=>x.id));return {...next,projects:[...next.projects,...old.projects.filter(x=>known.has(x.hostId)&&!online.has(x.hostId)&&!next.projects.some(p=>p.id===x.id))],sessions:[...next.sessions,...old.sessions.filter(x=>known.has(x.hostId)&&!online.has(x.hostId)&&!next.sessions.some(s=>s.id===x.id))]}});setLoaded(true)}catch(e){if(e instanceof ApiError&&(e.status===401||['401','UNAUTHORIZED'].includes(e.code))){rpc.close();setData(empty);setSelected(null);setDialog(null);try{const nextAuth=await http<Auth>('/api/auth');setAuth(nextAuth);if(nextAuth.authenticated)rpc.connect()}catch{setAuth(old=>old?{...old,authenticated:false}:{authenticated:false,mode:'oidc'})}}notify((e as Error).message)}},[rpc,notify]);
 useEffect(()=>{void http<Auth>('/api/auth').then(setAuth).catch(e=>setAuthError(e.message));return ()=>clearTimeout(refreshTimer.current)},[]);
 useEffect(()=>{document.documentElement.dataset.palette=palette;storePreference('polyhedron.palette',palette)},[palette]);useEffect(()=>storePreference('polyhedron.fontSize',String(fontSize)),[fontSize]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),6500);return ()=>clearTimeout(t)},[toast]);
 useEffect(()=>{let cancelled=false;setError('');setConflict(false);setHistory(null);historySession.current=null;historyRequest.current++;if(dialog?.kind==='history'){historySession.current=dialog.session.id;void loadHistory(dialog.session)}if(dialog?.kind==='settings'){setBrowsers(null);setBrowserError('');void http<{browsers:BrowserLogin[]}>('/api/browsers').then(result=>{if(!cancelled)setBrowsers(result.browsers)}).catch(e=>{if(!cancelled)setBrowserError(e.message)})}return()=>{cancelled=true}},[dialog]);
 useEffect(()=>{if(!auth?.authenticated)return;const a=rpc.onConnection(state=>{setConnection(state);if(state==='online')void refresh()}),b=rpc.subscribe(event=>{if(event.event==='state'){if(event.session)updateSession(event.session);if(event.host)setData(old=>({...old,hosts:event.host.revoked?old.hosts.filter(h=>h.id!==event.host.id):old.hosts.map(h=>h.id===event.host.id?{...h,...event.host}:h)}));clearTimeout(refreshTimer.current);refreshTimer.current=setTimeout(()=>void refresh(),180)}else if(event.event==='host'||event.event==='hosts')void refresh()});rpc.connect();void refresh();const timer=setInterval(()=>void refresh(),15000);return ()=>{a();b();rpc.close();clearInterval(timer)}},[auth?.authenticated,rpc,refresh,updateSession]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setFocus(false);requestAnimationFrame(()=>searchInput.current?.focus())}if((e.metaKey||e.ctrlKey)&&e.shiftKey&&e.key.toLowerCase()==='f'){e.preventDefault();setSearchOpen(x=>!x)}};window.addEventListener('keydown',key);return ()=>window.removeEventListener('keydown',key)},[]);
 const current=data.sessions.find(s=>s.id===selected),project=data.projects.find(p=>p.id===current?.projectId),host=data.hosts.find(h=>h.id===current?.hostId),canUse=connection==='online'&&!!host?.online;
 useEffect(()=>{if(current?.activity==='done'){setSeenCompletions(old=>{if(old[current.id]===current.updatedAt)return old;const next={...old,[current.id]:current.updatedAt};storePreference('polyhedron.seenCompletions',JSON.stringify(next));return next})}},[current?.id,current?.activity,current?.updatedAt]);
 const run=async(action:()=>Promise<unknown>,close=false)=>{if(busy)return;setBusy(true);setError('');try{await action();if(close)setDialog(null);await refresh()}catch(e){const message=(e as Error).message;setError(message);notify(message);if(e instanceof ApiError&&e.code==='PROJECT_BUSY')setConflict(true)}finally{setBusy(false)}};
 const request=<T,>(hostId:string,method:string,params:object={})=>rpc.request<T>(hostId,method,params);
 const close=()=>{if(!busy)setDialog(null)};
 const confirm=(title:string,description:string,action:()=>Promise<unknown>)=>setDialog({kind:'confirm',title,description,action});
 async function loadHistory(s:Session,older=false,runtimeEpoch?:string){setHistoryLoading(true);setError('');const version=++historyRequest.current;const before=older&&history?.entries.length?history.entries[0].seq:undefined;try{const result=await request<History>(s.hostId,'history',{sessionId:s.id,runtimeEpoch:runtimeEpoch||(older?history?.runtimeEpoch:s.runtimeEpoch),before,limit:150});if(historySession.current===s.id&&version===historyRequest.current)setHistory(old=>({...result,runs:result.runs??old?.runs,entries:older&&old?.runtimeEpoch===result.runtimeEpoch?[...result.entries,...old.entries]:result.entries}))}catch(e){if(historySession.current===s.id&&version===historyRequest.current)setError((e as Error).message)}finally{if(historySession.current===s.id&&version===historyRequest.current)setHistoryLoading(false)}}

 const submit=(event:FormEvent<HTMLFormElement>,action:(values:FormData)=>Promise<unknown>,closeAfter=true)=>{event.preventDefault();const values=new FormData(event.currentTarget);void run(()=>action(values),closeAfter)};
 if(!auth?.authenticated)return <main className="login-page"><section className="login-card"><Icon name="terminal"/><h1>多面体</h1><p>你的 Agent，随处继续。</p>{authError?<><p className="form-error" role="alert">{authError}</p><button className="primary" onClick={()=>location.reload()}>重新连接</button></>:!auth?<p role="status">正在连接…</p>:<>{auth.mode==='development'?<form onSubmit={e=>{e.preventDefault();setBusy(true);void http('/auth/dev',{}).then(()=>http<Auth>('/api/auth')).then(setAuth).catch(e=>setAuthError(e.message)).finally(()=>setBusy(false))}}><p className="settings-note">本机开发模式 · 仅限回环地址访问</p><button className="primary full-width" disabled={busy}>进入本机工作台</button></form>:<a className="primary full-width" href="/auth/login">登录并继续</a>}</>}</section></main>;
 const title=dialog?.kind==='settings'?'设置':dialog?.kind==='help'?'使用指南':dialog?.kind==='project'?'添加项目':dialog?.kind==='new'?'新建会话':dialog?.kind==='renameSession'?'重命名会话':dialog?.kind==='editProject'?'项目设置':dialog?.kind==='history'?'终端历史':dialog?.kind==='confirm'?dialog.title:'';
 return <main className={`page${focus?' focus-mode':''}`} id="workspace"><a className="skip-link" href="#terminal-workspace">跳到会话工作区</a><ShellHeader connection={connection} project={project} session={current} userName={auth.user?.name} focus={focus} onToggleFocus={()=>setFocus(x=>!x)} onOpenSettings={()=>setDialog({kind:'settings'})}/><div className="workbench-layout"><Sidebar hosts={data.hosts} projects={data.projects} sessions={data.sessions} loaded={loaded} connection={connection} filter={filter} query={query} collapsed={collapsed} selected={selected} seenCompletions={seenCompletions} searchInput={searchInput} onQueryChange={setQuery} onFilterChange={setFilter} onToggleProject={id=>setCollapsed(old=>{const next=new Set(old);next.has(id)?next.delete(id):next.add(id);return next})} onSelectSession={session=>{setSelected(session.id);setDetails(false)}} onAddProject={()=>setDialog({kind:"project"})} onCreateSession={project=>setDialog({kind:"new",project})} onEditProject={project=>setDialog({kind:"editProject",project})} onOpenHelp={()=>setDialog({kind:"help"})}/>
 <Workspace current={current} project={project} host={host} canUse={canUse} busy={busy} connection={connection} rpc={rpc} terminal={terminal} terminalVersion={terminalVersion} fontSize={fontSize} palette={palette} details={details} searchOpen={searchOpen} terminalQuery={terminalQuery} hasProjects={data.projects.length>0} hasHosts={data.hosts.length>0} onToggleDetails={()=>setDetails(value=>!value)} onReload={()=>setTerminalVersion(value=>value+1)} onToggleSearch={()=>setSearchOpen(value=>!value)} onSearchQuery={setTerminalQuery} onFind={previous=>{if(!terminal.current?.find(terminalQuery,previous))notify("未找到匹配文字")}} onCopy={()=>void terminal.current?.copy().catch(error=>notify(error.message))} onSession={updateSession} onError={notify} onConnectHost={()=>setDialog({kind:"settings"})} onAddProject={()=>setDialog({kind:"project"})} onClaim={()=>void run(async()=>{await terminal.current?.claim()})} onInterrupt={()=>void run(async()=>{await terminal.current?.interrupt()})} onRename={()=>current&&setDialog({kind:"renameSession",session:current})} onHistory={()=>current&&setDialog({kind:"history",session:current})} onResume={()=>current&&confirm("恢复会话",`在原主机和项目目录中恢复「${current.title}」，将启动新的 Agent 进程。`,async()=>{const session=await request<Session>(current.hostId,"resume",{sessionId:current.id});updateSession(session)})} onArchive={()=>current&&void run(async()=>{updateSession(await request<Session>(current.hostId,"archive",{sessionId:current.id,archived:!current.archived}))})} onTerminate={()=>current&&confirm("终止会话",`终止「${current.title}」的 Agent 进程及其受管理子进程。尚未保存的进程状态可能丢失。`,async()=>{await terminal.current?.terminate()})}/></div>
 {dialog&&<Modal title={title} onClose={close}>
 {dialog.kind==='project'&&<ProjectForm hosts={data.hosts} rpc={rpc} busy={busy} online={connection==='online'} onSubmit={e=>submit(e,async f=>{const p=await request<Project>(String(f.get('host')),'addProject',{name:String(f.get('name')).trim(),path:String(f.get('path')).trim()});setData(old=>({...old,projects:[...old.projects,p]}))})}/>}
 {dialog.kind==='new'&&<form onSubmit={e=>submit(e,async f=>{const s=await request<Session>(dialog.project.hostId,'createSession',{projectId:dialog.project.id,title:String(f.get('title')).trim(),agent:f.get('agent'),confirmConflict:f.get('confirmConflict')==='on'});updateSession(s);setSelected(s.id)})}><p className="dialog-description">会话将在此项目目录中启动真实 Agent。</p><Field label="会话名称" name="title" placeholder="例如：优化搜索体验"/><fieldset><legend>选择 Agent</legend>{(['codex','claude'] as Agent[]).map(a=>{const info=data.hosts.find(h=>h.id===dialog.project.hostId)?.agents?.find(x=>x.id===a);return <label key={a} className="agent-option" title={info?.reason}><input type="radio" name="agent" value={a} required disabled={!info?.available}/><span><strong>{agentName(a)}</strong><small>{info?.available?info.version||'已安装':info?.reason||'未检测到'}</small></span></label>})}</fieldset><div className="new-session-project"><p className="field-label">所属项目</p><strong>{dialog.project.name}</strong><p className="project-directory">{dialog.project.path}</p></div>{conflict&&<label className="conflict-check"><input type="checkbox" name="confirmConflict" required/>确认在同一目录并行运行；多个会话可能修改相同文件。</label>}<button className="primary full-width" disabled={busy}>创建会话</button><p className="dialog-disclaimer">CLI 的登录、信任和权限审批会显示在原生终端中。</p></form>}
 {dialog.kind==='renameSession'&&<form onSubmit={e=>submit(e,async f=>updateSession(await request<Session>(dialog.session.hostId,'renameSession',{sessionId:dialog.session.id,title:String(f.get('title')).trim()})))}><Field label="会话名称" name="title" initial={dialog.session.title}/><button className="primary full-width" disabled={busy}>保存名称</button></form>}
 {dialog.kind==='editProject'&&<><form onSubmit={e=>submit(e,async f=>{await request(dialog.project.hostId,'renameProject',{projectId:dialog.project.id,name:String(f.get('name')).trim()})})}><Field label="项目名称" name="name" initial={dialog.project.name}/><p className="project-directory">{dialog.project.path}</p><button className="primary full-width" disabled={busy||!data.hosts.find(h=>h.id===dialog.project.hostId)?.online}>保存名称</button></form><button className="text-button danger" disabled={busy||data.sessions.some(s=>s.projectId===dialog.project.id)||!data.hosts.find(h=>h.id===dialog.project.hostId)?.online} onClick={()=>confirm('移除项目',`移除「${dialog.project.name}」的项目记录，目录中的文件会保留。`,()=>request(dialog.project.hostId,'deleteProject',{projectId:dialog.project.id}))}>移除空项目</button><p className="dialog-description">包含会话的项目无法移除。</p></>}
 {dialog.kind==='settings'&&<><section className="settings-section"><div className="settings-heading"><h3>配色</h3><span className="palette-current">{palettes.find(p=>p[0]===palette)?.[1]}</span></div><div className="palette-options" role="group" aria-label="选择工作台配色">{palettes.map(([id,name,caption])=><button key={id} className="palette-option" data-palette={id} aria-pressed={palette===id} onClick={()=>{document.documentElement.dataset.palette=id;setPalette(id)}}><span className="palette-swatches" aria-hidden="true"><i/><i/><i/><i/></span><strong>{name}</strong><small>{caption}</small></button>)}</div></section><div className="settings-font"><label htmlFor="font-size">终端字号</label><input id="font-size" type="range" min="12" max="20" value={fontSize} onChange={e=>setFontSize(Number(e.target.value))}/><output>{fontSize}px</output></div><section className="settings-section"><h3>执行主机</h3>{data.hosts.length?data.hosts.map(h=><HostInfo key={h.id} host={h} busy={busy} onConfigure={settings=>void run(async()=>{await request(h.id,'configureHost',settings);notify('主机设置已保存')})} onRevoke={()=>confirm('解除主机绑定',`解除「${h.name}」与当前账号的绑定并断开连接。本机进程将继续运行。`,()=>http(`/api/hosts/${encodeURIComponent(h.id)}/revoke`,{},auth.csrfToken))}/>):<p className="dialog-description">尚未配对执行主机。</p>}<form className="pair-form" onSubmit={e=>submit(e,async f=>{await http('/api/pairings/approve',{code:String(f.get('code')).trim()},auth.csrfToken);notify('配对已确认，等待主机连接')},false)}><Field label="配对码" name="code" placeholder="输入主机安装程序显示的配对码"/><button className="primary" disabled={busy}>确认配对</button></form></section><section className="settings-section"><h3>浏览器登录</h3>{browserError?<p className="form-error">{browserError}</p>:browsers===null?<p className="dialog-description" role="status">正在读取登录记录…</p>:browsers.length?browsers.map(browser=><div className="browser-login" key={browser.id}><div><strong>登录于 {date(browser.createdAt)}</strong><small>到期时间 {date(browser.expiresAt)}</small></div>{browser.current?<span className="online-label">当前登录</span>:<button className="text-button danger" disabled={busy} onClick={()=>confirm('撤销浏览器登录',`撤销 ${date(browser.createdAt)} 的登录，相关窗口将断开连接。主机中的 Agent 进程会继续运行。`,()=>http(`/api/browsers/${encodeURIComponent(browser.id)}/revoke`,{},auth.csrfToken))}>撤销登录</button>}</div>):<p className="dialog-description">暂无有效登录记录。</p>}</section><section className="settings-section"><h3>账号与连接</h3><p className="dialog-description">{auth.user?.name} · {connection==='online'?'已连接':connection==='connecting'?'正在重连':'已断开'}</p><div className="session-actions"><button className="text-button" onClick={()=>{setFilter('archived');setDialog(null)}}>查看已归档会话</button><button className="text-button" disabled={busy} onClick={()=>{setBusy(true);void http('/auth/logout',{},auth.csrfToken).then(async()=>{rpc.close();setAuth(await http<Auth>('/api/auth'));setData(empty);setSelected(null);setDialog(null)}).catch(e=>setError(e.message)).finally(()=>setBusy(false))}}>退出登录</button></div></section></>}
 {dialog.kind==='help'&&<><p className="dialog-description">换台电脑，接着做。</p><ol className="help-steps"><li><span>1</span><div><strong>连接你的执行主机</strong><p>在主机安装并启动 Host 与 Connector，在设置中输入配对码。Agent CLI、项目文件与终端进程保留在该主机。</p></div></li><li><span>2</span><div><strong>按项目组织会话</strong><p>添加主机授权范围内的目录。在项目的悬浮菜单中选择“新建会话”，选择已安装的 Codex 或 Claude Code。</p></div></li><li><span>3</span><div><strong>接管后继续输入</strong><p>打开终端右上角的会话详情，点击接管控制。每次只有一个窗口可以输入，权限审批直接在 CLI 中完成。</p></div></li></ol><p className="settings-note">关闭页面不会停止 Agent。断线后会重新读取终端快照，未确认的输入不会自动重发。已结束的会话只有获得准确原生会话 ID 后才能恢复。</p><p className="dialog-description">⌘ / Ctrl K 搜索项目 · ⌘ / Ctrl Shift F 搜索终端</p></>}
 {dialog.kind==='history'&&<><p className="dialog-description">{dialog.session.title} · 只读历史，保留当前终端状态。</p>{history?.runs&&history.runs.length>1&&<label className="field-label field-block">运行记录<select className="form-control" aria-label="选择历史运行" value={history.runtimeEpoch} disabled={historyLoading} onChange={e=>void loadHistory(dialog.session,false,e.target.value)}>{history.runs.map((run,index)=><option key={run.runtimeEpoch} value={run.runtimeEpoch}>{date(run.createdAt)} · {run.runtimeEpoch===dialog.session.runtimeEpoch?'当前运行':`历史运行 ${index+1}`}</option>)}</select></label>}{history?.truncated&&<p className="settings-note">较早输出已达到主机保留上限。</p>}{history?.hasMore&&<button className="text-button" disabled={historyLoading} onClick={()=>void loadHistory(dialog.session,true)}>加载更早记录</button>}{historyLoading&&<p role="status">正在读取历史…</p>}<pre className="history-output" tabIndex={0}>{history?.entries.map(entry=>cleanHistory(entry.data)).join('')||(!historyLoading?'暂无历史输出':'')}</pre></>}
 {dialog.kind==='confirm'&&<><p className="dialog-description">{dialog.description}</p><div className="dialog-actions"><button className="secondary" onClick={close} disabled={busy}>取消</button><button className="primary" disabled={busy} onClick={()=>void run(dialog.action,true)}>确认</button></div></>}
 {error&&<p className="form-error" role="alert">{error}</p>}{busy&&<p className="dialog-disclaimer" role="status">正在处理，请稍候…</p>}</Modal>}
 {toast&&<div className="toast" role="status" aria-live="polite">{toast}<button aria-label="关闭提示" onClick={()=>setToast('')}>×</button></div>}</main>;
}
function HostInfo({host,onRevoke,onConfigure,busy}:{host:Host;onRevoke:()=>void;onConfigure:(settings:HostSettings)=>void;busy:boolean}){return <div className="host-entry"><div className="device-row"><span className="device-icon"><Icon name="computer"/></span><div><strong>{host.name}</strong><small>{host.platform||'执行主机'}</small></div><span className={host.online?'online-label':'muted'}>{host.online?'在线':'离线'}</span></div><details className="host-diagnostics"><summary>CLI 与目录</summary>{host.agents?.map(a=><p key={a.id}>{agentName(a.id)} · {a.available?a.version||'可用':a.reason||'不可用'}<small>{a.path}</small></p>)}{host.roots?.map(root=><p className="project-directory" key={root}>{root}</p>)}{!host.online&&<p>主机离线，CLI 状态暂不可用。</p>}<button className="text-button danger" onClick={onRevoke}>解除绑定</button></details><form className="host-settings" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onConfigure({preventSleep:f.get('preventSleep')==='on',historyDays:Number(f.get('historyDays')),maxHistoryBytes:Number(f.get('historyMiB'))*1024*1024})}}><label className="sleep-setting"><input type="checkbox" name="preventSleep" defaultChecked={host.settings?.preventSleep??false} disabled={!host.online||busy}/>任务运行时阻止空闲睡眠</label><div className="retention-fields"><label>历史保留（天）<input className="form-control" type="number" name="historyDays" min="1" max="365" defaultValue={host.settings?.historyDays??30} required disabled={!host.online||busy}/></label><label>历史容量（MiB）<input className="form-control" type="number" name="historyMiB" min="16" max="10240" defaultValue={Math.round((host.settings?.maxHistoryBytes??134217728)/1024/1024)} required disabled={!host.online||busy}/></label></div><button className="text-button" disabled={!host.online||busy}>保存主机设置</button></form></div>}
